version: '3.4'
services:
  server:
    image: "cernoch/venus-docker-server"
    ports:
     - "8088:8088"
#    volumes:
#     - "./venus-server:/config"
  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host
  influxdb:
    image: "influxdb:1.7"
    ports:
     - "8086:8086"
    volumes:
     - "./influxdb:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
  influxdb2:
    image: "influxdb:2.6"
    ports:
     - "8087:8086"
  graphing:
    image: "victronenergy/venus-docker-grafana:latest"
    volumes:
     - "./grafana-data:/var/lib/grafana"
    ports:
     - "3000:3000"
